package main

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"
	_ "github.com/qsrrvln/mountapi/docs" // docs is generated by Swag CLI
	"github.com/qsrrvln/mountapi/internal/config"
	"github.com/qsrrvln/mountapi/internal/database"
	"github.com/qsrrvln/mountapi/internal/handlers"
	"github.com/qsrrvln/mountapi/internal/middleware"
	"github.com/qsrrvln/mountapi/internal/models"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Mountain API
// @version 1.0
// @description API for Mountain Hiking Data in Indonesia
// @host localhost:8080
// @BasePath /v1
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name X-API-Key
func main() {
	// 1. Load Config
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// 2. Connect Database
	db, err := database.ConnectDB(cfg)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	// 3. Auto Migrate (for development convenience)
	if err := models.Migrate(db); err != nil {
		log.Fatalf("Failed to migrate database: %v", err)
	}
	log.Println("Database migrated successfully")

	// 4. Setup Router
	r := gin.Default()

	// Public Group
	mountainHandler := handlers.NewMountainHandler(db)
	routeHandler := handlers.NewRouteHandler(db)
	v1 := r.Group("/v1")
	{
		v1.GET("/mountains", mountainHandler.GetMountains)
		v1.GET("/mountains/:id", mountainHandler.GetMountain)
		v1.GET("/mountains/:id/routes", mountainHandler.GetMountainRoutes)

		v1.GET("/routes/:id", routeHandler.GetRoute)
		v1.GET("/routes/:id/posts", routeHandler.GetRoutePosts)
	}

	// Admin Group (Protected)
	postHandler := handlers.NewPostHandler(db)
	admin := r.Group("/v1")
	admin.Use(middleware.AuthMiddleware(cfg))
	{
		// Mountains
		admin.POST("/mountains", mountainHandler.CreateMountain)
		admin.PUT("/mountains/:id", mountainHandler.UpdateMountain)
		admin.PATCH("/mountains/:id", mountainHandler.PatchMountain)
		admin.DELETE("/mountains/:id", mountainHandler.DeleteMountain)

		// Routes
		admin.POST("/routes", routeHandler.CreateRoute)
		admin.PUT("/routes/:id", routeHandler.UpdateRoute)
		admin.PATCH("/routes/:id", routeHandler.PatchRoute)
		admin.DELETE("/routes/:id", routeHandler.DeleteRoute)

		// Posts
		admin.POST("/posts", postHandler.CreatePost)
		admin.PUT("/posts/:id", postHandler.UpdatePost)
		admin.PATCH("/posts/:id", postHandler.PatchPost)
		admin.DELETE("/posts/:id", postHandler.DeletePost)
		admin.POST("/posts/bulk", postHandler.BulkUploadPosts)
	}

	// Swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	serverAddr := fmt.Sprintf(":%s", cfg.ServerPort)
	log.Printf("Server starting on %s", serverAddr)
	if err := r.Run(serverAddr); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
